### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by LyndisCealin** [LyndisCealin/Stories#1]
My To-Do list for the Website

- [ ] Tag Explanation Page in Blog
- [ ] Sort Chapters by index not by Date (therefore I can update a Chapter with a new date but it's still in the right place)
- [ ] complete this To-Do list
- [ ] Publish all the scripts you've written (with proper explanation)
